# Generated by Django 4.2.7 on 2024-02-03 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_alter_package_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutInActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Food', max_length=100, null=True, verbose_name='どのようにして過ごすのが好きですか？')),
            ],
            options={
                'verbose_name_plural': 'インドアアウトドア',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='core_app.outinactivity', verbose_name='どのようにして過ごすのが好きですか❓'),
        ),
    ]
