# Generated by Django 4.2.7 on 2024-02-03 05:32

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0017_outinactivity_package_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='scat', unique=True, verbose_name='id')),
                ('title', models.CharField(blank=True, default='Food', max_length=100, null=True, verbose_name='お気に入りの旅行のアクティビティ何ですか？')),
            ],
            options={
                'verbose_name_plural': '旅行のアクティビティ',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='personality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personality', to='core_app.personality', verbose_name='お気に入りの旅行のアクティビティ何ですか？❓'),
        ),
    ]
