# Generated by Django 4.2.7 on 2024-02-03 05:33

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0018_personality_package_personality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='scat', unique=True, verbose_name='id')),
                ('title', models.CharField(blank=True, default='Food', max_length=100, null=True, verbose_name='公共交通機関アクセス')),
            ],
            options={
                'verbose_name_plural': '公共交通機関アクセス',
            },
        ),
        migrations.RemoveField(
            model_name='package',
            name='location',
        ),
        migrations.RemoveField(
            model_name='package',
            name='prefecture',
        ),
        migrations.AddField(
            model_name='package',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport', to='core_app.transport', verbose_name='公共交通機関アクセス'),
        ),
    ]
