# Generated by Django 4.2.7 on 2024-02-03 05:35

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0019_transport_remove_package_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='scat', unique=True, verbose_name='カテゴリーのid')),
                ('title', models.CharField(blank=True, default='Food', max_length=100, null=True, verbose_name='subカテゴリー名')),
            ],
            options={
                'verbose_name_plural': 'subカテゴリー',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='core_app.subcategory', verbose_name='場所の中にあるもの'),
        ),
    ]
