# Generated by Django 4.2.7 on 2024-02-03 05:36

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0020_subcategory_package_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='scat', unique=True, verbose_name='id')),
                ('title', models.CharField(blank=True, default='Food', max_length=100, null=True, verbose_name='駐車場')),
            ],
            options={
                'verbose_name_plural': '駐車場',
            },
        ),
        migrations.AddField(
            model_name='package',
            name='parking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking', to='core_app.parking', verbose_name='駐車場'),
        ),
    ]
