# Generated by Django 4.2.7 on 2024-02-03 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0022_location_package_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='core_app.outinactivity', verbose_name='インドアアウトドア❓'),
        ),
    ]
