# Generated by Django 4.2.7 on 2024-02-03 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0023_alter_package_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.section', verbose_name='セクション'),
        ),
    ]
