# Generated by Django 4.2.7 on 2024-02-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0024_alter_package_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='search',
        ),
    ]
