# Generated by Django 4.2.7 on 2024-02-03 08:22

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0025_remove_package_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': '場所の中にあるもの'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='scid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=20, prefix='scat', unique=True, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(blank=True, default='Food', max_length=100, null=True, verbose_name='場所の中にあるもの'),
        ),
    ]
