# Generated by Django 4.2.7 on 2024-02-08 01:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0026_alter_subcategory_options_alter_subcategory_scid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='specification',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
